version: "3"
services:
  nginx:
    image: nginx:stable
    container_name: lpa_reverse_proxy
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 9001:80
    depends_on:
      - backend
      - frontend

  backend:
    image: linkedpipes/applications:backend
    container_name: lpa_backend
    build:
      context: src/backend/
    volumes:
      - ./src/backend/config.properties:/app/config.properties:ro

  frontend:
    image: linkedpipes/applications:frontend
    container_name: lpa_frontend
    build:
      context: src/frontend/

  db:
    image: tenforce/virtuoso:1.3.2-virtuoso7.2.2
    environment:
      SPARQL_UPDATE: "true"
      DEFAULT_GRAPH: "http://www.example.com/my-graph"
    volumes:
      - ./data/virtuoso:/data

  # Discovery service runs locally in port 9000
  discovery:
    image: linkedpipes/applications:discovery
    container_name: lpa_discovery
    command: -Dldcp.etl.hostname="http://etl:8080" -Dplay.crypto.secret=yourRandomSecret
    stdin_open: true
    depends_on:
      - db
      - etl

  etl:
    image: linkedpipes/etl
    container_name: lpa_etl
    # ports:
    #   - 1234:8080
