version: "3"
services:
  nginx:
    image: nginx:stable
    container_name: lpa_reverse_proxy
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 80:80
    depends_on:
      - backend
      - frontend

  backend:
    image: linkedpipes/applications:backend
    container_name: lpa_backend
    build:
      context: src/backend/
    volumes:
      - ./src/backend/config.properties:/app/config.properties:ro
    ports:
      - 9005:8080
    depends_on:
      - etl
      - discovery

  frontend:
    image: linkedpipes/applications:frontend
    container_name: lpa_frontend
    build:
      context: src/frontend/
      dockerfile: Dockerfile-prod
    # depends_on:
    #   - backend

  db:
    image: tenforce/virtuoso:1.3.2-virtuoso7.2.2
    container_name: lpa_virtuoso
    environment:
      SPARQL_UPDATE: "true"
      DEFAULT_GRAPH: "http://www.example.com/my-graph"
    ports:
      - 8890:8890
    volumes:
      - ./data/virtuoso:/data

  discovery:
    image: linkedpipes/applications:discovery
    container_name: lpa_discovery
    command:
      [
        "-Dldcp.etl.hostname=http://lpa_etl:8080",
        "-Dplay.http.secret.key=yourRandomSecret",
      ]
    ports:
      - 9000:9000
    # depends_on:
    #   - db
    #   - etl

  etl:
    image: linkedpipes/etl
    container_name: lpa_etl
    ports:
      - 8080:8080
