version: "3"
services:
  nginx:
    image: nginx:stable
    container_name: lpa-reverse-proxy
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 9001:80
    depends_on:
      - backend
      - frontend

  backend:
    image: linkedpipes/applications:backend
    container_name: lpa-backend
    build:
      context: src/backend/
    volumes:
      - ./src/backend/config.properties:/app/config.properties:ro
    ports:
      - 9005:8080
    depends_on:
      - etl
      - discovery

  frontend:
    image: linkedpipes/applications:frontend
    container_name: lpa-frontend
    build:
      context: src/frontend/
      dockerfile: Dockerfile
    depends_on:
      - backend

  db:
    image: tenforce/virtuoso:1.3.2-virtuoso7.2.2
    container_name: lpa-virtuoso
    environment:
      SPARQL_UPDATE: "true"
      DEFAULT_GRAPH: "http://www.example.com/my-graph"
    ports:
      - 8890:8890
    volumes:
      - ./data/virtuoso:/data

  discovery:
    image: linkedpipes/applications:discovery
    container_name: lpa-discovery
    command:
      [
        "40",
        "-Dldcp.etl.hostname=http://lpa-etl:8080",
        "-Dplay.http.secret.key=yourRandomSecret",
        "-Dpidfile.path=/dev/null",
      ]
    depends_on:
      - db
      - etl
    ports:
      - 9000:9000

  etl:
    image: linkedpipes/etl
    container_name: lpa-etl
    ports:
      - 8080:8080
